---
title: ''
summary: ''
date: 2022-10-24
type: landing

sections:
  - block: resume-biography-3
    content:
      username: me
      text: ''
      headings:
        about: 'About Me'
        education: ''
        interests: ''
    design:
      background:
        gradient_mesh:
          enable: false

      spacing:
        padding: ['30px', '0', '40px', '0']

      name:
        size: md

      avatar:
        size: medium
        shape: circle
